author = "David Hwang"
baseurl = "/"
canonifyurls = true
copyright = "Copyright © 2008–2019, David Hwang; all rights reserved."
paginate = 3
theme = "alageek"
title = "David Hwang"

[params]
copyright = "© 2019 by David Hwang"
copyrightUrl = "https://davidhwang.me"
faviconfile = "/img/nine_dots.ico"
latestpostcount = 5
logofile = "https://gokmengorgen.net/img/laughing-man.png"
highlightjs = true
linkedin = "david-hwang"
twitter = "hwangmoretime"
github = "hwangmoretime"

[[params.best_posts]]
title = "Creating A New Theme"
url = "/blog/creating-a-new-theme/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.secondary]]
identifier = "patreon"
name = "Become a patron"
url = "https://www.patreon.com/bePatron?u=10637849"
weight = 110

[[menu.secondary]]
identifier = "bmc"
name = "Buy me a coffee"
url = "https://www.buymeacoffee.com/gokmen"
weight = 120
