author = "Gökmen Görgen"
baseurl = "/"
canonifyurls = true
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
theme = "alageek"
title = "alaGeek Theme"

[params]
copyright = "© 2018 by Gökmen Görgen"
copyrightUrl = "https://gokmengorgen.net"
faviconfile = "https://gokmengorgen.net/img/laughing-man-favicon.png"
latestpostcount = 5
logofile = "https://gokmengorgen.net/img/laughing-man.png"
highlightjs = true

[[params.best_posts]]
title = "Migrate to Hugo from Jekyll"
url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.secondary]]
identifier = "patreon"
name = "Become a patron"
url = "https://www.patreon.com/bePatron?u=10637849"
weight = 110

[[menu.secondary]]
identifier = "bmc"
name = "Buy me a coffee"
url = "https://www.buymeacoffee.com/gokmen"
weight = 120
