name = "alaGeek"
license = "MIT"
licenselink = "https://github.com/gkmngrgn/hugo-alageek-theme/blob/master/LICENSE.md"
description = "alaGeek website specific theme."
homepage = "https://alageek.com"
tags = ["clean", "fast", "responsive", "typography"]
features = ["flexible", "fast", "highlights", "progressive images"]
min_version = 0.40.3

[author]
  name = "Gökmen Görgen"
  homepage = "https://gokmengorgen.net"

[original]
    name = "Alexis Tacnet"
    homepage = "https://fuegowolf.me/"
    repo = "https://github.com/fuegowolf/cocoa-eh-hugo-theme"
